#!/usr/bin/env python3

import os
from db import init_db
from web.app import create_app

print("ONLY FOR DEVELOPMENT USE!!! DANGEROUS ENV VARS SET !!!!")

os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "True"

if __name__ == "__main__":
    init_db()
    app = create_app()
    app.run(debug=True)
